version: '3.9'
services:
  videos.izdrail.com:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER:-1000}'
        WWWGROUP: '${WWWGROUP:-1001}'
    image: izdrail/videos.izdrail.com
    container_name: videos.izdrail.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '1603:1603'
      - '1604:1604'
    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'
      LARAVEL_SAIL: 1
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      IMAGE_GENERATION_ENABLED: 'true'
      IMAGE_GENERATION_MODEL: 'stabilityai/sd-turbo'
      IMAGE_GENERATION_DEVICE: 'auto'
      VISUAL_SOURCE: 'stock'
      HF_HOME: '/opt/huggingface_models'
    volumes:
      - '.:/app'
      - './cache/images:/app/cache/images'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - sail

networks:
  sail:
    driver: bridge
