version: '3.9'
services:
  videos.izdrail.com:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER:-1000}'
        WWWGROUP: '${WWWGROUP:-1001}'
    image: izdrail/videos.izdrail.com
    container_name: videos.izdrail.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '1602:1602'
    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'
      LARAVEL_SAIL: 1
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/app'
    networks:
      - sail

networks:
  sail:
    driver: bridge
