[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=debug  ; Full debug logs for both services

; ==========================
; Video PYTHON BACKEND
; ==========================
[program:video-generator]
command=python3 -u main.py     ; "-u" ensures unbuffered stdout for instant logs
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/video-generator.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/supervisor/video-generator.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3



; ==========================
; Video PYTHON BACKEND
; ==========================
[program:slides-generator]
command=python3 -u slides-main.py     ; "-u" ensures unbuffered stdout for instant logs
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/slides-generator.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/supervisor/slides-generator.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3





; ==========================
; Video MEME BACKEND
; ==========================
[program:meme-generator]
command=python3 -u meme-main.py     ; "-u" ensures unbuffered stdout for instant logs
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/meme-generator.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/var/log/supervisor/meme-generator.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3